### ISSUE TITLE
Crashing on android

### ISSUE THREAD

**Issue by Venryx** [Lichwa/react-native-file-picker#3]
Crashes on Android whenever I select a file, or even press the back button to cancel.

Note that the Javascript handler is completely empty, so it's not due to my doing something strange post-selection.

Error stack trace:
```
11-20 06:05:31.027: D/AndroidRuntime(12249): Shutting down VM
11-20 06:05:31.029: E/AndroidRuntime(12249): FATAL EXCEPTION: main
11-20 06:05:31.029: E/AndroidRuntime(12249): Process: com.lucidlink, PID: 12249
11-20 06:05:31.029: E/AndroidRuntime(12249): java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:260)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:627)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:135)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread.access$1300(ActivityThread.java:151)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.os.Looper.loop(Looper.java:135)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at java.lang.reflect.Method.invoke(Native Method)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
11-20 06:05:33.508: I/Process(12249): Sending signal. PID: 12249 SIG: 9
```

**Comment by Venryx** [comment]
Okay, I figured it out. Sort of. Enough to get it to work at least.

Apparently there are two versions of react-native getting used in my project: one for compile-time, on for run-time.

The run-time one wanted the onActivityResult method to have an Activity argument, like this:
public void onActivityResult(Activity activity, final int requestCode, final int resultCode, final Intent data) {}

The compile time one (older, apparently) did not want the Activity arg. So like this
public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {}

Anyway, thought I'd mention it on the remote chance it has something to do with this project, rather than just some oddity of how my project has evolved, as I've added and updated packages.

**Comment by ishabo** [comment]
@Venryx Thanks for this! I am having the same issue, see a similar error in my crashalytics report. However, I am not sure I understand your solution.  Can you please elaborate? Much thanks!

**Comment by Venryx** [comment]
Just add one of the two lines below, to the FilePickerModule.java file:
```
public void onActivityResult(Activity activity, final int requestCode, final int resultCode, final Intent data) {}
```

```
public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {}
```

Add whichever of those two is not there already.

If you still get the error, then try moving the code from the old method override into the new one.

**Comment by luisfuertes** [comment]
Must add at end: 
``` 
    public void onActivityResult(Activity activity, final int requestCode, final int resultCode, final Intent data) {
      // user cancel
      if (resultCode != Activity.RESULT_OK) {
          response.putBoolean("didCancel", true);
          mCallback.invoke(response);
          return;
      }

      Activity currentActivity = getCurrentActivity();

      Uri uri;

      if (requestCode == REQUEST_LAUNCH_FILE_CHOOSER) {
          uri = data.getData();
          response.putString("uri", data.getData().toString());
          String path = null;
          path = getPath(currentActivity, uri);
          if (path != null) {
              response.putString("path", path);
          }
          mCallback.invoke(response);
      }
    }


    // Required for RN 0.30+ modules than implement ActivityEventListener
    public void onNewIntent(Intent intent) { }
``` 

But now only give the file uri, yesterday it return path also :s
